# -*- coding: utf-8 -*-
"""Hk1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153T5l3yLpfncgXLnH4yaJxbud0Sy0FAm
"""

pip install pgmpy

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import ExpectationMaximization as EM
import pandas as pd

# Sample data with missing values (None)
data = pd.DataFrame([
    ['True', 'Yes'],
    ['False', 'No'],
    ['True', 'None'],   # Missing value here
    ['False', 'No'],
    ['True', 'Yes']
], columns=['Weather', 'Play'])

# Define the network structure
model = DiscreteBayesianNetwork([('Weather', 'Play')])

# Run EM to estimate CPDs from incomplete data
em = EM(model, data)
model = em.get_parameters()

# Print learned CPDs
for cpd in model:
    print(cpd)